"""
Simple circular orbit simulator for CubeSat attitude estimation testing.

Generates a deterministic ground-truth attitude trajectory combining:
  - Orbital nadir-pointing rotation (driven by mean motion)
  - Slow sinusoidal tumble superimposed on top

Provides the BE-01 Dynamics Simulator interface: true quaternion and
true angular velocity per time step.
"""

import numpy as np
from ..ekf.quaternion import from_euler, normalize
from ..ekf.kinematics import xi_matrix

_MU      = 3.986004418e14  # Earth gravitational parameter [m³/s²]
_R_EARTH = 6.3781e6        # Earth equatorial radius [m]


def orbital_period(altitude_km: float) -> float:
    """Keplerian period for a circular orbit at given altitude [s]."""
    r = _R_EARTH + altitude_km * 1e3
    return 2.0 * np.pi * np.sqrt(r ** 3 / _MU)


class CircularOrbit:
    """
    Circular equatorial orbit with a superimposed sinusoidal tumble.

    Interface (BE-01 Dynamics Simulator):
      true_attitude(t)          — ground-truth quaternion [q0, q1, q2, q3]
      true_angular_velocity(t)  — body-frame angular velocity [rad/s]
      state(t)                  — structured dict: true_quaternion + true_angular_velocity
      magnetic_field_inertial() — normalized reference magnetic field vector
    """

    def __init__(self, altitude_km: float = 500.0, tumble_rate_deg_s: float = 0.1):
        self.altitude_km = altitude_km
        self.period      = orbital_period(altitude_km)
        self._n          = 2.0 * np.pi / self.period   # mean motion [rad/s]
        self._tumble     = np.deg2rad(tumble_rate_deg_s) * np.array([0.3, 0.5, 0.2])

    def true_attitude(self, t: float) -> np.ndarray:
        """
        Ground-truth quaternion at time t [s].
        Combines slow nadir-pointing yaw with sinusoidal roll and pitch.
        """
        yaw   = self._n * t
        roll  = 0.15 * np.sin(self._tumble[0] * t)
        pitch = 0.10 * np.sin(self._tumble[1] * t + 0.5)
        return normalize(from_euler(roll, pitch, yaw))

    def true_angular_velocity(self, t: float, dt: float = 1e-5) -> np.ndarray:
        """
        Body-frame angular velocity at time t via quaternion finite difference.

        Uses ω = 2 Ξ(q)ᵀ q̇, where q̇ is approximated by central differences.
        This is exact as dt → 0; 1e-5 s gives sub-µrad/s accuracy for the
        smooth trajectories generated by this simulator.
        """
        q_prev = self.true_attitude(t - dt)
        q_next = self.true_attitude(t + dt)
        q_now  = self.true_attitude(t)
        q_dot  = (q_next - q_prev) / (2.0 * dt)
        return 2.0 * xi_matrix(q_now).T @ q_dot

    def state(self, t: float) -> dict:
        """
        Return BE-01 ground-truth state dict at time t.

        Keys:
          true_quaternion        — np.ndarray [q0, q1, q2, q3]
          true_angular_velocity  — np.ndarray [wx, wy, wz] rad/s
        """
        return {
            "true_quaternion":       self.true_attitude(t),
            "true_angular_velocity": self.true_angular_velocity(t),
        }

    def magnetic_field_inertial(self) -> np.ndarray:
        """
        Normalized Earth magnetic field in the inertial frame.
        Simplified dipole model representative of a 500 km LEO equatorial orbit.
        """
        b = np.array([0.3090, 0.0, 0.9511])
        return b / np.linalg.norm(b)
