import { FlaskConical } from "lucide-react";
import { useSimulationStore } from "@/stores/simulationStore";

/**
 * Sticky top-of-page notice shown whenever mode === "simulate".
 * Reminds the operator that all values are physics-model outputs,
 * not real satellite telemetry.
 */
export function SimulationModeBanner() {
  const mode = useSimulationStore((s) => s.mode);
  if (mode !== "simulate") return null;

  return (
    <div className="sticky top-0 z-20 flex items-center gap-2.5 border-b border-amber-500/25 bg-amber-500/10 px-5 py-2 text-xs text-amber-400">
      <FlaskConical className="h-3.5 w-3.5 shrink-0" />
      <span>
        <span className="font-semibold">Simulation mode —</span> all sensor readings and attitude
        estimates are generated by a physics model and do not represent real satellite data.
      </span>
    </div>
  );
}
